# Generated by Django 4.2.6 on 2024-12-13 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_cart_total_alter_items_but_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='but_price',
            field=models.FloatField(default=0.0),
        ),
    ]
