# Generated by Django 4.2.6 on 2024-12-13 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_items_but_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='but_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='items',
            name='selling_price',
            field=models.IntegerField(default=0.0),
        ),
    ]
